#!/bin/bash
ARGS="$@"
jarfile="$(ls -t target/*.jar | head -1)"
if [[ -f "$jarfile" ]]; then
  java -jar $jarfile PshGP $ARGS
else
  mvn "-Dexec.args=-classpath %classpath org.spiderland.Psh.PshInspector $ARGS" -Dexec.executable=java -Dexec.classpathScope=runtime org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
fi

